steps:

- script: pip install pytest pytest-cov coverage codecov
  displayName: 'Install testing tools'
  continueOnError: false

- script: catchsegv xvfb-run -a -s "-screen 0 1280x1024x24" pytest orangecontrib/bioinformatics/tests --doctest-modules --junitxml=junit/test-results.xml --cov=orangecontrib.bioinformatics --cov-report=xml --cov-report=html
  condition: in(variables['Agent.OS'], 'Linux')
  displayName: 'Run pytest'

- script: pytest orangecontrib/bioinformatics/tests --doctest-modules --junitxml=junit/test-results.xml --cov=orangecontrib.bioinformatics --cov-report=xml --cov-report=html
  condition: in(variables['Agent.OS'], 'Darwin', 'Windows_NT')
  displayName: 'Run pytest'

- script: codecov -f coverage.xml -F adder -F subtractor
  displayName: 'Upload codecov'
  env:
    CODECOV_TOKEN: $(codecov.token)


#  - task: PublishCodeCoverageResults@1
#    displayName: 'Publish code coverage'
#    condition: succeededOrFailed()
#    inputs:
#      codeCoverageTool: Cobertura
#      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
#      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: '${{ parameters.platform }} - Python $(python.version)'